Repository cardano-foundation/cardano-graphql, pull requests merged in 2020-07, with the labels that each got.

#203 Chore/docs update
  packages/cli/README.md
  packages/server/README.md
  packages/util-dev/README.md
Labels: admin

#202 Fix hasura path regression with nixos service
  nix/nixos/cardano-graphql-service.nix
  release.nix
Labels: bug

#201 Establish relationships to easily access transaction and block information from inputs and outputs
  Jenkinsfile
  packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
  packages/api-cardano-db-hasura/schema.graphql
  packages/api-cardano-db-hasura/src/example_queries/utxos/utxoSetForAddress.graphql
  packages/api-cardano-db-hasura/test/blocks.query.test.ts
  packages/api-cardano-db-hasura/test/cardano.query.test.ts
  packages/api-cardano-db-hasura/test/epochs.query.test.ts
  packages/api-cardano-db-hasura/test/graphql_operations/getAnyUtxoAddress.graphql
  packages/api-cardano-db-hasura/test/transactions.query.test.ts
  packages/api-cardano-db-hasura/test/util.ts
  packages/api-cardano-db-hasura/test/utxos.query.test.ts
  packages/cli/test/util.ts
Labels: enhancement

#206 Localise devDeps required by npm scripts
  packages/api-cardano-db-hasura/package.json
  packages/cli/package.json
  packages/server/package.json
  packages/util-dev/package.json
  packages/util/package.json
Labels: DevOps

#208 Fix/block fees view type correction
  packages/api-cardano-db-hasura/hasura/pre-start.sh
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1590383124093_add_transaction_block_index/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1590383124093_add_transaction_block_index/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/up.sql
  packages/cli/src/Docker/commands/rebuildService.ts
Labels: bug

#210 Feature/db sync progress awareness
  README.md
  docker-compose.yml
  packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593917265153_add_cardano_slots_per_epoch/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593917265153_add_cardano_slots_per_epoch/up.sql
  packages/api-cardano-db-hasura/package.json
  packages/api-cardano-db-hasura/schema.graphql
  packages/api-cardano-db-hasura/src/DB.ts
  packages/api-cardano-db-hasura/src/example_queries/cardano/dynamic.graphql
  packages/api-cardano-db-hasura/src/executableSchema.ts
  packages/api-cardano-db-hasura/src/lib/DeepPartial.ts
  packages/api-cardano-db-hasura/src/lib/scalar_resolvers.ts
  packages/api-cardano-db-hasura/src/lib/scalars/DateTime.ts
  packages/api-cardano-db-hasura/src/lib/scalars/Lovelaces.ts
  packages/api-cardano-db-hasura/src/lib/scalars/Percentage.ts
  packages/api-cardano-db-hasura/test/__snapshots__/cardano.query.test.ts.snap
  packages/api-cardano-db-hasura/test/__snapshots__/epochs.query.test.ts.snap
  packages/api-cardano-db-hasura/test/blocks.query.test.ts
  packages/api-cardano-db-hasura/test/cardano.query.test.ts
  packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
  packages/api-cardano-db-hasura/test/data_assertions/epoch_assertions.ts
  packages/api-cardano-db-hasura/test/dataparitytests/blocks.parity.test.ts
  packages/api-cardano-db-hasura/test/epochs.query.test.ts
  packages/server/test/Server.test.ts
  packages/server/test/app_with_graphql_operations/src/feature_1/cardanoDynamic.graphql
  packages/util-dev/src/e2e_client.ts
  packages/util/package.json
  packages/util/src/dateTimeValidation.ts
  packages/util/src/index.ts
  packages/util/src/scalars/DateTimeUtcToIso.ts
  packages/util/src/scalars/Hash32HexString.ts
  packages/util/src/scalars/Percentage.ts
  packages/util/src/scalars/index.ts
  test/postgres/dump_when_block_height_reached.sh
  yarn.lock
Labels: bug, enhancement

#211 Release/1.0.0 rc.13
  CHANGELOG.md
  docker-compose.yml
  package.json
  packages/api-cardano-db-hasura/package.json
  packages/cli/package.json
  packages/cli/src/Docker/docker-compose.yml
  packages/client-ts/package.json
  packages/server/package.json
  packages/util-dev/package.json
  packages/util/package.json
Labels: admin

#213 Fix/package definitions
  packages/api-cardano-db-hasura/package.json
  packages/api-cardano-db-hasura/src/executableSchema.ts
  packages/server/package.json
  packages/util-dev/package.json
  packages/util/package.json
Labels: bug

#215 Bump to cardano-node 1.14.2
  docker-compose.yml
Labels: admin

#217 Chore/doc updates
  README.md
  packages/api-cardano-db-hasura/src/example_queries/meta/cardanoDbSyncProgress.graphql
  packages/cli/README.md
Labels: docs

#218 Fix/retain ci test stack between runs
  Jenkinsfile
  packages/api-cardano-db-hasura/hasura/docker-entrypoint.sh
  packages/util-dev/src/e2e_client.ts
Labels: DevOps

#224 refactor(cardano-db-sync): Introduce dayjs
  packages-cache/dayjs-1.8.29.tgz
  packages/api-cardano-db-hasura/package.json
  packages/api-cardano-db-hasura/src/DB.ts
  yarn.lock
Labels: refactor

#225 fix(api-cardano-db-hasura): handle migrations in application
  .eslintignore
  Dockerfile
  Jenkinsfile
  docker-compose.yml
  nix/nixos/cardano-graphql-service.nix
  package.json
  packages-cache/@babel-runtime-7.5.0.tgz
  packages-cache/@types-set-interval-async-1.0.0.tgz
  packages-cache/set-interval-async-1.0.33.tgz
  packages/api-cardano-db-hasura/README.md
  packages/api-cardano-db-hasura/hasura/Dockerfile
  packages/api-cardano-db-hasura/hasura/docker-entrypoint.sh
  packages/api-cardano-db-hasura/hasura/pre-start.sh
  packages/api-cardano-db-hasura/images/powered_by_hasura_blue.svg
  packages/api-cardano-db-hasura/package.json
  packages/api-cardano-db-hasura/src/DB.ts
  packages/api-cardano-db-hasura/src/Db.ts
  packages/api-cardano-db-hasura/src/executableSchema.ts
  packages/api-cardano-db-hasura/src/index.ts
  packages/api-cardano-db-hasura/test/util.ts
  packages/server/src/config.ts
  packages/server/src/index.ts
  packages/server/test/Server.test.ts
  yarn.lock
Labels: bug

#239 feat(client-ts): include api-genesis in client-ts package
  packages/client-ts/api/genesis/index.ts
  packages/client-ts/codegen.cardano-db-hasura.yml
  packages/client-ts/codegen.genesis.yml
  packages/client-ts/package.json
  packages/client-ts/scripts/cleanup.sh
  packages/client-ts/scripts/embed_schema.sh
Labels: enhancement

#240 fix(api-genesis): corrects valid nullable fields in the genesis model
  packages/api-genesis/schema.graphql
  packages/api-genesis/test/genesis.query.test.ts
Labels: bug

#244 chore: Optional API segments, update to support multiple genesis files
  Jenkinsfile
  config/network/mainnet/genesis_shelley.json
  config/network/mainnet_candidate/genesis_shelley.json
  config/network/shelley_testnet/genesis_shelley.json
  docker-compose.yml
  package.json
  packages/api-cardano-db-hasura/test/util.ts
  packages/api-genesis/test/__snapshots__/genesis.query.test.ts.snap
  packages/api-genesis/test/genesis.query.test.ts
  packages/server/package.json
  packages/server/src/config.ts
  packages/server/src/index.ts
  packages/util-dev/src/e2e_client.ts
Labels: enhancement

#245 adding "distinct on address" capability to utxo queries.
  packages/api-cardano-db-hasura/schema.graphql
Labels: enhancement

#246 chore: nest Shelley genesis to formalise the era
  docker-compose.yml
  package.json
  packages/api-genesis/schema.graphql
  packages/api-genesis/src/example_queries/allInfo.graphql
  packages/api-genesis/src/example_queries/keyNetworkInfo.graphql
  packages/api-genesis/test/__snapshots__/genesis.query.test.ts.snap
  packages/server/src/index.ts
  packages/server/test/Server.test.ts
Labels: enhancement

#247 Feature/shelley models
  Jenkinsfile
  config/network/mainnet/cardano-node/config.json
  config/network/mainnet/cardano-node/topology.json
  config/network/mainnet/genesis_byron.json
  config/network/mainnet/genesis_shelley.json
  config/network/mainnet_candidate/genesis_shelley.json
  config/network/mainnet_candidate_3/cardano-node/config.json
  config/network/mainnet_candidate_3/cardano-node/topology.json
  config/network/mainnet_candidate_3/genesis_byron.json
  config/network/mainnet_candidate_3/genesis_shelley.json
  config/network/shelley_testnet/cardano-node/config.json
  config/network/shelley_testnet/cardano-node/topology.json
  config/network/shelley_testnet/genesis_shelley.json
  config/network/testnet/cardano-node/config.json
  config/network/testnet/cardano-node/topology.json
  config/network/testnet/genesis_byron.json
  config/network/testnet/genesis_shelley.json
  docker-compose.yml
  docs/public/android-chrome-192x192.png
  docs/public/android-chrome-512x512.png
  docs/public/apple-touch-icon.png
  docs/public/favicon-16x16.png
  docs/public/favicon-32x32.png
  docs/public/favicon.ico
  docs/public/index.html
  docs/public/site.webmanifest
  package.json
  packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1590383124093_add_transaction_block_index/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1590383124093_add_transaction_block_index/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593691353254_block_fees_to_big_int/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593917265153_add_cardano_slots_per_epoch/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1593917265153_add_cardano_slots_per_epoch/up.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_hfc_compat_slot_in_epoch/down.sql
  packages/api-cardano-db-hasura/hasura/project/migrations/1594274227099_hfc_compat_slot_in_epoch/up.sql
  packages/api-cardano-db-hasura/schema.graphql
  packages/api-cardano-db-hasura/src/Db.ts
  packages/api-cardano-db-hasura/src/example_queries/blocks/blocksByHashes.graphql
  packages/api-cardano-db-hasura/src/executableSchema.ts
  packages/api-cardano-db-hasura/test/data_assertions/block_assertions.ts
  packages/api-cardano-db-hasura/test/dataparitytests/epochs.parity.test.ts
  packages/api-cardano-db-hasura/test/dataparitytests/transactions.parity.test.ts
Labels: enhancement

#249 Chore/bump service deps
  Jenkinsfile
  docker-compose.yml
  package.json
  packages-cache/create-next-app-9.3.5.tgz
  packages/api-cardano-db-hasura/src/example_queries/epochs/numberOfBlocksProducedByLeaderInEpoch.graphql
  packages/api-cardano-db-hasura/test/epochs.query.test.ts
  packages/api-genesis/package.json
  packages/api-genesis/schema.graphql
  packages/server/src/tsconfig.json
  packages/server/test/Server.test.ts
  packages/server/test/app_with_graphql_operations/src/feature_1/maxLovelaceSupply.graphql
  packages/server/test/app_with_graphql_operations/src/feature_2/maxLovelaceSupplyAndSystemStart.graphql
Labels: dependencies

#250 feat(api-genesis): Add Byron genesis model to API
  package.json
  packages/api-genesis/schema.graphql
  packages/api-genesis/src/example_queries/allInfoShelley.graphql
  packages/api-genesis/src/example_queries/keyNetworkInfoByronShelley.graphql
  packages/api-genesis/src/example_queries/keyNetworkInfoShelley.graphql
  packages/api-genesis/src/executableSchema.ts
  packages/api-genesis/test/__snapshots__/genesis.query.test.ts.snap
  packages/api-genesis/test/genesis.query.test.ts
  packages/server/src/index.ts
Labels: enhancement

#252 Chore/update network config
  config/network/mainnet/cardano-db-sync/config.json
  config/network/mainnet/cardano-node/config.json
  config/network/mainnet/genesis/byron.json
  config/network/mainnet/genesis/shelley.json
  config/network/mainnet_candidate_3/cardano-node/topology.json
  config/network/mainnet_candidate_3/genesis_shelley.json
  config/network/mainnet_candidate_4/cardano-db-sync/config.json
  config/network/mainnet_candidate_4/cardano-node/config.json
  config/network/mainnet_candidate_4/cardano-node/topology.json
  config/network/mainnet_candidate_4/genesis/byron.json
  config/network/mainnet_candidate_4/genesis/shelley.json
  config/network/shelley_testnet/cardano-node/config.json
  config/network/shelley_testnet/genesis_shelley.json
  config/network/testnet/cardano-db-sync/config.json
  config/network/testnet/cardano-node/config.json
  config/network/testnet/genesis/byron.json
  config/network/testnet/genesis/shelley.json
  config/network/testnet/genesis_shelley.json
  docker-compose.yml
  package.json
  packages/api-genesis/test/genesis.query.test.ts
  packages/server/test/Server.test.ts
Labels: refactor

#259 Fix/nullable transaction outputs
  Jenkinsfile
  package.json
  packages-cache/create-next-app-9.3.5.tgz
  packages/api-cardano-db-hasura/schema.graphql
  packages/api-cardano-db-hasura/test/blocks.query.test.ts
  packages/api-cardano-db-hasura/test/cardano.query.test.ts
  packages/api-cardano-db-hasura/test/epochs.query.test.ts
  packages/api-cardano-db-hasura/test/transactions.query.test.ts
  packages/api-cardano-db-hasura/test/util.ts
  packages/api-cardano-db-hasura/test/utxos.query.test.ts
  packages/util-dev/src/e2e_client.ts
Labels: bug

#261 Corrects nullable fields, fix delegation to pool relationship
  packages/api-cardano-db-hasura/hasura/project/metadata/tables.yaml
  packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql
  packages/api-cardano-db-hasura/schema.graphql
  packages/api-cardano-db-hasura/test/queries/shelleyEraQueries.graphql
  packages/api-cardano-db-hasura/test/shelley.query.test.snap.ts.txt
  packages/api-cardano-db-hasura/test/shelley.query.test.ts
  packages/api-cardano-db-hasura/test/transactions.query.test.ts
Labels: bug
